'use client'

// מדור "מחקר מלא" בדף החכם — נטען בצד הלקוח מ-/research/<id>.json
// (עובד זהה בלוקאל וב-Vercel; הקבצים סטטיים ב-public/research)
import { useEffect, useState } from 'react'
import type { Locale } from '@/lib/types'
import { ReadingControls, useReadingPrefs, readingStyle } from '@/components/ui/ReadingControls'
import { tr } from '@/lib/i18n'

interface ResearchDoc {
  title: string
  source_file: string
  word_count: number
  content: string
}

export function ResearchSection({ sageId, locale }: { sageId: string; locale: Locale }) {
  const [docs, setDocs] = useState<ResearchDoc[] | null>(null)
  const [isFallback, setIsFallback] = useState(false)
  const [prefs, setPrefs] = useReadingPrefs()
  const isHe = locale === 'he'

  // Localized research: /research/<id>.<locale>.json (generated by the
  // Character Factory translate_research script), falling back to the
  // canonical Hebrew /research/<id>.json when no translation exists yet.
  useEffect(() => {
    let alive = true
    const fetchDocs = async () => {
      if (locale !== 'he') {
        try {
          const r = await fetch(`/research/${sageId}.${locale}.json`)
          if (r.ok) {
            const d = await r.json()
            if (alive) { setDocs(Array.isArray(d) ? d : []); setIsFallback(false) }
            return
          }
        } catch { /* fall through to Hebrew */ }
      }
      try {
        const r = await fetch(`/research/${sageId}.json`)
        const d = r.ok ? await r.json() : []
        if (alive) { setDocs(Array.isArray(d) ? d : []); setIsFallback(locale !== 'he') }
      } catch {
        if (alive) setDocs([])
      }
    }
    fetchDocs()
    return () => { alive = false }
  }, [sageId, locale])

  if (docs === null) {
    return (
      <p className="text-xs font-sans text-ink-500 animate-pulse">
        {tr(locale, 'טוען מחקר…', 'Loading research…', 'Загрузка исследования…')}
      </p>
    )
  }
  if (docs.length === 0) return null

  return (
    <section>
      <div className="flex items-center justify-between gap-3 mb-3">
        <h2 className="text-xs font-sans font-semibold uppercase tracking-widest text-ink-500">
          {isHe
            ? `מחקר מלא (${docs.length} ${docs.length === 1 ? 'מסמך' : 'מסמכים'})`
            : locale === 'ru'
              ? `Полное исследование (${docs.length} док.)`
              : `Full Research (${docs.length} ${docs.length === 1 ? 'document' : 'documents'})`}
        </h2>
        <ReadingControls prefs={prefs} onChange={setPrefs} locale={locale} />
      </div>
      {isFallback && (
        <p className="text-[11px] font-sans text-ink-500 mb-2">
          {locale === 'ru'
            ? 'Исследование пока доступно только на иврите.'
            : 'Research is currently available in Hebrew only.'}
        </p>
      )}
      <div className="space-y-3" dir={isFallback || isHe ? 'rtl' : 'ltr'}>
        {docs.map((doc, i) => (
          <details key={i} open={i === 0}
            className="rounded-xl border border-ink-700/40 bg-ink-800/30 overflow-hidden">
            <summary className="cursor-pointer select-none px-4 py-3 font-serif text-sm text-gold-300 hover:bg-ink-700/30 transition-colors">
              📖 {doc.title.length > 90 ? doc.title.slice(0, 90) + '…' : doc.title}
              <span className="text-ink-500 text-xs font-sans"> · {doc.word_count.toLocaleString()} {tr(locale, 'מילים', 'words', 'слов')}</span>
            </summary>
            <div
              className="px-4 pb-4 pt-1 text-sm text-ink-200 whitespace-pre-line border-t border-ink-700/30"
              style={readingStyle(prefs)}
            >
              {doc.content}
            </div>
          </details>
        ))}
      </div>
    </section>
  )
}
